### ISSUE TITLE
Execption Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by marneu** [gedl/gc-csv#1]
This would be the perfect thing I am looking for to do my backups.

./gc-csv-0.0.7.jar -h

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/gccsv/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

OS: Ubuntu
using: default-jre 2:1.7-51

**Comment by gedl** [comment]
Hi @marneu

Apologies for the late reply. I hadn't noticed somebody was actually trying to use this.

This is because this tool was compiled for Java 1.8 and you are running Java 1.7. I was using a few Java 1.8 features but they were few enough for me to remove them.

I have released another version (https://github.com/gedl/gc-csv/releases/tag/0.0.9) that runs on Java 1.5. 

I will close this issue now, please do reopen if you can't get this to work.
